# ==========================================
# APLICAÇÃO
# ==========================================

spring.application.name=FinTrackAPI


# ==========================================
# BANCO H2
# ==========================================

spring.datasource.url=jdbc:h2:file:./data/fintrack
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ==========================================
# CONSOLE H2
# ==========================================

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# ==========================================
# SERVIDOR
# ==========================================

server.port=8080

# ==========================================
# JWT
# ==========================================

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
